# Describes the format for available ADS services
mob_notify:
  description: 'Wysłanie powiadomienia do aplikacji AIS-dom.'
  fields:
    device_id:
      description: 'Identyfikator urządzenia.'
      example: 'mobile_ais_dom-'
      selector:
        device:
          integration: mobile_app
          entity:
            domain: device_tracker
    message:
      description: 'Tekst wiadomości'
      example: 'Dzwonek do drzwi.'
      selector:
        text:
    title:
      description: 'Tytuł powiadomienia'
      example: 'Powiadomienie z AI-Speaker.'
      selector:
        text:
    image:
      description: 'URL obrazu do wyświetlenia w powiadomieniu (plik max 1MB dostępny z Internetu)'
      example: 'http://ai-speaker.com/images/doorbell.jpg'
      selector:
        text:
    priority:
      description: 'Priorytet wiadomości normal albo high'
      example: 'high'
      selector:
        select:
          options:
            - "normal"
            - "high"
    say:
      description: 'Czy wiadomość po odebraniu ma być przeczytana na telefonie.'
      example: true
      selector:
        boolean:
    notification_id:
      description: 'Unikalny numer powiadomienia, jeśli wyślesz powiadomienie z tym samym numerem, to powiadomienie będzie nadpisywane.'
      example: '0'
      selector:
        number:
          min: 0
          max: 10000
    click_action:
      description: 'Nawigacja do widoku który mamy zdefiniowany w aplikacji np.: /lovelace/camera lub otwarcie strony internetowej o dowolnym adresie URL, np.: https://ai-speaker.com'
      example: '/lovelace/0'
      selector:
        text:

mob_request:
  description: 'Wysłanie komendy (zapytania/żądania) do aplikacji mobilnej. Ta usługa wymaga aplikacji AIS dom w wersji 1.3.0 lub nowszej.'
  fields:
    device_id:
      description: 'Identyfikator urządzenia.'
      example: 'mobile_ais_dom-'
      selector:
        device:
          integration: mobile_app
          entity:
            domain: device_tracker
    request:
      description: 'Komenda'
      example: 'micOn'
      selector:
        select:
          options:
            - "locationUpdate"
            - "micOn"
    data:
      description: 'Dodatkowe dane komendy (opcjonalnie)'
      example: '{}'
      selector:
        object:

check_local_ip:
  description: 'Sprawdzenie lokalnego IP bramki i ustawienie go jako wartość encji sensor.internal_ip_address. Ta usługa wykonaywana jest automatycznie przy starcie urządzenia.'

check_night_mode:
  description: 'Sprawdzenie czy został włączony tryb nocny jeżeli tak to zmieniamy motyw aplikacji na ciemniejszy i redukujemy głośność. Ta usługa wykonaywana jest co minutę.'

on_new_iot_device_selection:
  description: 'Ustalenie nazwy nowododawanego urządzenia. Ta usługa wykonaywana jest automaycznie podczas dodawania nowego urządzenia.'
  fields:
    iot:
      description: 'Model urządzenia.'
      example: 's20'

prepare_remote_menu:
  description: 'Przygotowanie menu dostępnego z pilota na podstawie grup/encji w systemie. Ta usługa wykonywana jest automatycznie po uruchomieniu systemu oraz po wykryciu/dodaniu nowych komponentów.'

process:
  description: 'Zamiana tekstu na komendę do wykonania.'
  fields:
    text:
      description: 'Tekst pynia/komendy.'
      example: 'Włącz radio RMF'
      selector:
        text:

process_code:
  description: 'Przetwarzanie kodu z klawiatury/pilota. Ta usługa wykonywana jest automatycznie po otrzymaniu kodu z klawiatury/pilota.'
  fields:
    text:
      description: 'Wiadomość z kodem z pilota oraz akcją (0 - down, 1 - up, 2 - hold)'
      example: '{"text": "{\"KeyCode\": 92, \"Action\": \"0\"}"} '
      selector:
        object:

process_command_from_frame:
  description: 'Przetwarzanie wiadomości/komendy otrzymanej z systemu Android.'
  fields:
    data:
      description: 'Przykładowy komunikat o zmianie adresu IP.'
      example: '{"topic": "ais/ip_state_change_info", "payload": "{\"ip\": \"192.168.1.1\"}"}'
      selector:
        object:

publish_command_to_frame:
  description: 'Publikowanie komendy do systemu Android.'
  fields:
    key:
      description: 'Akcja do wykonania.'
      example: 'playAudio'
      selector:
        select:
          options:
            - "micOn"
            - "micOff"
            - "playAudio"
            - "stopAudio"
            - "setVolume"
            - "goToActivity"
            - "showCamera"
    val:
      description: 'Wiadomość / dane do akcji.'
      example: 'https://test/audio.mp3'
      selector:
        text:

say_in_browser:
  description: 'Wysłanie tekstu do przeczytania w przeglądarce'
  fields:
    text:
      description: 'Tekst do przeczytania przez przeglądarkę'
      example: 'Cześć, tu przeglądarka'
      selector:
        text:

say_it:
  description: 'Zamiana tekstu na mowę, czytanie tekstu. Za pomocą mechanizmu TTS w systemie Android na bramce.'
  fields:
    text:
      description: 'Tekst do przeczytania.'
      example: 'Cześć, jak się masz'
      selector:
        text:
    pitch:
      description: 'Ton mowy. 1.0 to normalny ton, niższe wartości obniżają ton syntetyzowanego głosu, większe wartości go zwiększają.'
      example: '1.0'
      selector:
        number:
          step: 0.1
          min: 0.1
          max: 3
    rate:
      description: 'Szybkość mowy. 1.0 to normalna szybkość mowy, niższe wartości spowalniają mowę (0,5 to połowa normalnej szybkości mowy), większe wartości ją przyspieszają (2,0 to dwukrotność normalnej szybkości mowy)..'
      example: '1.0'
      selector:
        number:
          step: 0.1
          min: 0.1
          max: 5
    language:
      description: 'Język. Inne dostępne opcje to np. uk_UA, en_GB, en_US'
      example: 'pl_PL'
      selector:
        select:
          options:
            - "pl_PL"
            - "uk_UA"
            - "en_GB"
            - "en_US"
    voice:
      description: 'pl_PL: Jola, Celina, Anżela, Asia, Sebastian, Bartek, Andrzej. uk_UA: Mariya. en_GB: Allison, Jon. en_US: Sophia, Sam'
      example: 'Jola'
      selector:
        select:
          options:
            - "Jola"
            - "Celina"
            - "Anżela"
            - "Asia"
            - "Sebastian"
            - "Bartek"
            - "Andrzej"
            - "Mariya"
            - "Allison"
            - "Jon"
            - "Sophia"
            - "Sam"
    path:
      description: 'Ścieżka do zapisu pliku w formacie wav na dysku wewnętrznym w urządzeniu'
      example: 'komunikaty/otwarte_drzwi_wejściowe_pl.wav'
      selector:
        text:

set_context:
  description: 'Ustawienie kontekstu w jakim jest konwersacja z asystentem'
  fields:
    text:
      description: 'Kontekst do ustawienia'
      example: 'youtube'

welcome_home:
  description: 'Głosowy komunikat powitalny. Akcja wykonywana jest automatycznie podczas uruchomienia systemu.'
