# Describes the format for available AIS cloud services
get_podcast_names:
  description: Pobranie nazw podcastów dla wybranego typu
  fields:
    podcast_type:
      description: Typ podcasta.
      example: 'Humor'

get_podcast_tracks:
  description: Pobranie odcinków wybranego podcasta.
  fields:
    podcast_name:
      description: Nazwa podcasta.
      example: 'Home Assistant'

get_podcast_types:
  description: Pobranie typów podcastów

get_radio_names:
  description: Pobranie nazw stacji radiowych dla wybranego typu
  fields:
    radio_type:
      description: Typ radia.
      example: 'Informacyjne'

get_radio_types:
  description: Pobranie typów stacji radiowych

get_rss_news_channels:
  description: Pobranie kanałów z wiadomościami
  fields:
    rss_news_category:
      description: Kategoria wiadomości.
      example: 'Kultura'

get_rss_news_items:
  description: Pobranie wiadomości dla wybranego kanału
  fields:
    rss_news_channel:
      description: Kanał wiadomości.
      example: 'Kultura w RMF24'

play_audio:
  description: Odtwarzanie audio wybranego typu
  fields:
    audio_type:
      description: Typ audio do odtwarzania.
      example: 'Radio'
    name:
      description: Nazwa audio do odtwarzania.
      example: 'Trójka'
    stream_url:
      description: Url do audio.
      example: 'http://radio/program3/stream.mp3'
    image_url:
      description: Url do okładki.
      example: 'http://radio/program3/image.png'

select_media_player:
  description: Wybranie / zmiana odtwarzacza audio
  fields:
    media_player_type:
      description: Typ odtwarzacza.
      example: 'Radio'

select_rss_help_item:
  description: Wybranie strony pomocy do przeczytania
  fields:
    rss_help_topic:
      description: Strona pomocy.
      example: '2. Co nowego'

get_backup_info:
  description: Pobiera informacje o stanie kopii zapasowej ustawień w portalu integratora i zapisuje je do sensora ais_backup_info

set_backup_step:
  description: Ustawia status kopi zapasowej
  fields:
    step:
      description: Numer kroku w procesie backup
      example: '1'

do_backup:
  description: Wykonuje kopie ustawień, szyfruje je podanym hasłem i przesyła do portalu integratora
  fields:
    password:
      description: Hasło do zabezpieczenia kopii ustawień
      example: 'sekret123'

restore_backup:
  description: Pobiera kopie ustawień z portalu integratora i rozpakowuje je na bramce używając podanego hasła
  fields:
    password:
      description: Hasło do rozpakowania kopii ustawień
      example: 'sekret123'

enable_gate_pairing_by_pin:
  description: Włącza możliwość parowania z bramką za pomocą jednorazowego kodu PIN
