- id: '201807081853001'
  alias: 'AIS Asystent domowy Witamy'
  initial_state: True
  trigger:
  - event: start
    platform: homeassistant
  action:
   - service: ais_shell_command.set_io_scheduler
     data:
       scheduler: noop
   - service: ais_shell_command.start_sip_server
   - delay: '6'
   - service: ais_ai_service.publish_command_to_frame
     data:
       key: WifiConnectionInfo
       val: true
   - service: ais_ai_service.publish_command_to_frame
     data:
       key: getAudioStatus
       val: true
   - service: ais_ai_service.publish_command_to_frame
     data:
       key: getTtsVoice
       val: true
   - service: ais_shell_command.init_local_sdcard
   - service: ais_shell_command.set_ais_secure_android_id_dom
   - service: ais_updater.check_version
     data:
       autoUpdate: false
       sayIt: false
   - service: ais_bookmarks.get_favorites
   - service: ais_bookmarks.get_bookmarks
   - service: ais_cloud.get_radio_types
   - service: ais_cloud.get_podcast_types
   - service: ais_cloud.get_rss_news_category
   - service: ais_yt_service.search
   - service: ais_audiobooks_service.get_authors
   - service: ais_shell_command.disable_irda_remote
   - service: ais_ai_service.check_local_ip
   - service: ais_amplifier_service.get_audio_mono
   - service: ais_shell_command.hdmi_control_disable
   - service: ais_usb.stop_devices
   - service: mqtt.publish
     data:
       payload: 1
       topic: dom/cmnd/SetOption19
   - service: mqtt.publish
     data:
       payload: 1
       topic: cmnd/dom/SetOption19
   - service: mqtt.publish
     data:
       payload: 0
       topic: dom/cmnd/state
   - service: mqtt.publish
     data:
       payload: 0
       topic: cmnd/dom/state
   - service: ais_ai_service.prepare_remote_menu
   - service: ais_shell_command.change_remote_access
   - service: ais_ai_service.check_night_mode
     data:
       timer: false
   - service: ais_usb.check_ais_usb_settings
   - service: ais_usb.lsusb
   - service: ais_usb.mount_external_drives
   - service: ais_usb.ls_flash_drives
   - service: ais_drives_service.rclone_mount_drives
   - service: ais_ai_service.welcome_home
   - delay: '600'
   - service: ais_shell_command.set_scaling_governor
     data:
       scaling: interactive
   - delay: '6000'
   - service: ais_updater.check_version
     data:
       autoUpdate: true
       sayIt: false
- id: '201807081858006'
  alias: 'AIS Get RSS Help Items For Selected Topic'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.ais_rss_help_topic
  action:
    - service: ais_cloud.select_rss_help_item
      data_template:
        rss_help_topic: "{{ states('input_select.ais_rss_help_topic') }}"

- id: '201807081905011'
  alias: 'AIS Ask The Question'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_text.ais_knowledge_query
  condition:
    condition: template
    value_template: "{{ states.input_text.ais_knowledge_query.state != '' }}"
  action:
    - service: conversation.process
      data_template:
        text: "{{ states('input_text.ais_knowledge_query') }}"

- id: '201807081905012'
  alias: 'AIS Search YouTube Tracks'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_text.ais_music_query
  action:
    - service: ais_yt_service.search
      data_template:
        query: "{{ states('input_text.ais_music_query') }}"

- id: '2018070819050123'
  alias: 'AIS Search Spotify Tracks'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_text.ais_spotify_query
  action:
    - service: ais_spotify_service.search
      data_template:
        query: "{{ states('input_text.ais_spotify_query') }}"

- id: '201807081916015'
  alias: 'AIS Get RSS News Channels'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.rss_news_category
  action:
    - service: ais_cloud.get_rss_news_channels
      data_template:
        rss_news_category: "{{ states('input_select.rss_news_category') }}"

- id: '201807081916016'
  alias: 'AIS Get RSS News Items'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.rss_news_channel
  action:
    - service: ais_cloud.get_rss_news_items
      data_template:
        rss_news_channel: "{{ states('input_select.rss_news_channel') }}"

- id: '201807081919019'
  alias: 'AIS Get Podcast Names'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.podcast_type
  action:
    - service: ais_cloud.get_podcast_names
      data_template:
        podcast_type: "{{ states('input_select.podcast_type') }}"

- id: '201807081923022'
  alias: 'AIS Get Radio Names'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.radio_type
  condition:
    condition: template
    value_template: "{{ states.input_select.radio_type.state != '-' }}"
  action:
    - service: ais_cloud.get_radio_names
      data_template:
        radio_type: "{{ states('input_select.radio_type') }}"

- id: '201807081923025'
  alias: 'AIS Change Player Speed'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_number.media_player_speed
  action:
    - service: ais_ai_service.publish_command_to_frame
      data_template:
        key: "setPlaybackSpeed"
        val: "{{ states('input_number.media_player_speed') }}"

- id: '201808231617123'
  alias: 'AIS Select Device To Add'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.ais_iot_devices_in_network
  condition:
    condition: template
    value_template: "{{ states.input_select.ais_iot_devices_in_network.state != '-' }}"
  action:
    - service: ais_ai_service.on_new_iot_device_selection
      data_template:
        iot: "{{ states('input_select.ais_iot_devices_in_network') }}"

- id: '201809171610123'
  alias: 'AIS Select Bookmark To Play'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.ais_bookmark_last_played
  condition:
    condition: template
    value_template: "{{ states.input_select.ais_bookmark_last_played.state != '-' }}"
  action:
    - service: ais_bookmarks.play_bookmark
      data_template:
        bookmark: "{{ states('input_select.ais_bookmark_last_played') }}"

- id: '201809291519123'
  alias: 'AIS Flush logs'
  initial_state: True
  trigger:
    platform: time
    at: '05:15:00'
  action:
    - service: ais_shell_command.flush_logs

- id: '201902030742123'
  alias: 'AIS Change remote web access'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.ais_remote_access
  action:
    - service: ais_shell_command.change_remote_access

- id: '201994281100123'
  alias: 'AIS Discovery info to dom devices'
  initial_state: True
  trigger:
    platform: time_pattern
    minutes: '/59'
  action:
    - service: mqtt.publish
      data:
        payload: 1
        topic: dom/cmnd/SetOption19
    - service: mqtt.publish
      data:
        payload: 1
        topic: cmnd/dom/SetOption19

- id: '201905201824123'
  alias: 'AIS Check WiFi Connection'
  initial_state: True
  trigger:
    platform: time_pattern
    minutes: '/15'
  action:
    - service: ais_ai_service.publish_command_to_frame
      data:
        key: WifiConnectionInfo
        val: true

- id: '201906171602001'
  alias: 'AIS Get Books'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.book_autor
  action:
    - service: ais_audiobooks_service.get_books
      data_template:
        author: "{{ states('input_select.book_autor') }}"

- id: '201906251757001'
  alias: 'AIS Change Equalizer Mode'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.media_player_sound_mode
  action:
    - service: media_player.select_sound_mode
      data_template:
        entity_id: "media_player.wbudowany_glosnik"
        sound_mode: "{{ states('input_select.media_player_sound_mode') }}"


- id: '20190810123'
  alias: 'AIS Change audio to mono'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.ais_audio_mono
  action:
    - service: ais_amplifier_service.change_audio_to_mono

- id: '201911121415123'
  alias: 'AIS set WiFi config for devices'
  initial_state: True
  trigger:
    platform: time
    at: '18:35:00'
  action:
    - service: mqtt.publish
      data:
        payload: 4
        topic: dom/cmnd/WifiConfig

- id: '201911151800123'
  alias: 'AIS IFTTT info'
  initial_state: True
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: say_it
  action:
    - data_template:
        text: '{{ trigger.event.data.text }}'
        img: '{{ trigger.event.data.img }}'
      service: "ais_ai_service.say_it"

- id: '20210630144002'
  alias: 'AIS Change Audio Routing'
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.ais_audio_routing
  action:
    - service: ais_amplifier_service.set_audio_routing
      data_template:
        routing: "{{ states('input_select.ais_audio_routing') }}"