homeassistant:
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named ais_packages/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 0.0.0.0/0
        - ::1
    - type: homeassistant
    - type: legacy_api_password
      api_password: dom
  allowlist_external_dirs:
    - /data/data/pl.sviete.dom/files/home/AIS/www/

  auth_mfa_modules:
    - type: totp
      name: "AIS Multi-factor authentication"
#
system_health:

# Track the sun
sun:

# ais-dom cloud functionality
ais_cloud:
ais_ai_service:
ais_knowledge_service:
ais_shell_command:
ais_yt_service:
ais_updater:
  include_used_components: false
ais_drives_service:

# Enables a map showing the location of tracked devices
map:

#
media_extractor:

# Enables the frontend
frontend:
  # development_repo: ~/Projects/AIS-home-assistant-polymer
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  server_port: 8180
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# AIS Service for AI
# Allows you to issue voice commands
mqtt: !include mqtt.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# bookmarks and favorites
ais_bookmarks:

#
ais_audiobooks_service:
#
# ais_spotify_service:
ais_wifi_service:

#
ais_amplifier_service:

#
person:

ais_help:
ais_virtual_devices:

conversation:
scene:
mobile_app:
ais_usb:

zone:

logger:
  default: info

# set up Zeroconf and make AIS dom discoverable
ais_mdns:

# serve local files
media_source:

# ais ingress
ais_auto_proxy:
#
ais_web_zigbee2mqtt:
  host: localhost
  port: 8099

ais_web_zwave2mqtt:
  host: localhost
  port: 8091

ais_files:

google:
  client_id: ASK_AIS_DOM
  client_secret: ASK_AIS_DOM

webhook:
counter:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
tag:
timer:
my:

tts:
  - platform: ais_tts_local

zeroconf: