# Describes the format for available AIS amplifier services
change_audio_to_mono:
  description: Włączenie lub wyłączenie dzwięku mono
  fields:
    mode:
      description: Dzwięk mono
      example: True
      selector:
        boolean:

get_audio_mono:
  description: Sprawdzenie czy dzwięk jest mono czy stereo (uruchamiane automatycznie podczas startu systemu)

change_work_mode:
  description: Ustawienie trybu działania wzmacniacza
  fields:
    mode:
      description: Tryb dzialania wzmacniacza, wybór z listy
      example: "AX"
      selector:
        select:
          options:
            - "AX"
            - "BT"

change_sound_mode:
  description: Ustawienie trybu działania equalizera
  fields:
    mode:
      description: Tryb dzialania equalizera, wybór z listy
      example: "ROCK"
      selector:
        select:
          options:
            - "NORMAL"
            - "BOOST"
            - "TREBLE"
            - "POP"
            - "ROCK"
            - "CLASSIC"
            - "JAZZ"
            - "DANCE"
            - "R&P"

exec_command:
  description: Przesłanie instrukcji sterującej do wzmacniacza
  fields:
    command:
      description: Instrukcja sterująca
      example: 'V16'
      selector:
        object:

exec_tonos_command:
  description: Przesłanie instrukcji sterującej do wzmacniacza TONOS
  fields:
    command:
      description: Instrukcja sterująca
      example: 'V0'
      selector:
        object:

set_audio_routing:
  description: (PRO) Ustawienie przekierowania wyjścia audio w Android
  fields:
    routing:
      description: Przekierowanie wyjścia audio
      example: 'all'
      selector:
        select:
          options:
            - "all"
            - "hdmi"
            - "spdif"
            - "jack"