sensor:
  # Sensor for monitoring the bridge state
  - platform: mqtt
    name: Status Serwisu Zigbee2mqtt
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:usb-port

  # Sensor for Showing the Zwave2mqtt Version
  - platform: mqtt
    name: Status Serwisu ZwaveJs2mqtt
    state_topic: "zwave/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt/status"
    value_template: "{{ value_json.value }}"
    icon: mdi:zwave

