add_item:
  description: Adds an item to the ais tts list.
  fields:
    name:
      description: The name of the item to add.
      example: Hello
complete_item:
  description: Marks an item as selected in the ais tts list
  fields:
    name:
      description: The name of the item to mark as selected.
      example: Hello
play_item:
  description: Czytanie tekstu z aplikacji
  fields:
    item:
      description: Numer pozycji do przeczytania.
      example: 0
change_auto_mode:
  description: Zmiana automatyzacji
  fields:
    entity_id:
      description: Identyfikator automatyzacji
      example: 0
    change_to:
      description: Zmiana na
      example: "on"
stop_talking:
  description: Zatrzymanie mówienia
